### ISSUE TITLE
bccomp error in scripts/Buckets.php

### ISSUE THREAD

**Issue by TiagoValdo** [Insideall/dfp-prebid-lineitems#12]
As stated by php docs, the bccomp function takes two strings to perform the comparison.
The code is using numeric values directly, which causes some values to fail the comparison and therefore, some line items will be missing.

to fix that, the bccomp functions need to have the operands converted to strings:

```php
for ($i = $value['min']; bccomp(sprintf('%F', $i), sprintf('%F', $value['max']), $precision) <= 0; $i += $value['increment']) {
	if ($i > 0 && 0 !== bccomp(sprintf('%F', $i), sprintf('%F', $lastValue), 2)) {
		array_push($buckets, sprintf("%0.{$precision}f", $i));
	}
	$lastValue = $i;
}
```

**Comment by gchicoye** [comment]
You need to install bccomp
https://www.php.net/manual/en/bc.installation.php
